# Generated by Django 6.0.4 on 2026-05-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_task_user_task_assignees_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees',
            new_name='assigned_to',
        ),
    ]
